# Generated by Django 5.2.3 on 2025-06-24 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_post_scrapped_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project_type',
            field=models.TextField(choices=[('team_project', '조별과제'), ('project', '프로젝트'), ('competition', '공모전'), ('supporters', '서포터즈'), ('etc', '기타')], default='', verbose_name='프로젝트 유형'),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 1), verbose_name='프로젝트 시작일'),
            preserve_default=False,
        ),
    ]
