# Generated by Django 5.2.3 on 2025-06-24 04:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Team',
        ),
        migrations.RenameModel(
            old_name='GroupMember',
            new_name='TeamMember',
        ),
    ]
