# Generated by Django 5.2.3 on 2025-06-24 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_group_team_rename_groupmember_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='댓글')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.team')),
            ],
        ),
    ]
