# Generated by Django 5.2.3 on 2025-06-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_team_project_field_remove_team_project_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='target',
        ),
    ]
