# Generated by Django 5.2.3 on 2025-06-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_type', models.TextField(choices=[('project', '프로젝트'), ('competition', '공모전'), ('supporters', '서포터즈'), ('etc', '기타')], default='', verbose_name='프로젝트 유형')),
                ('project_field', models.TextField(choices=[('planning', '기획/아이디어'), ('development', '개발'), ('design', '디자인'), ('marketing', '마케팅'), ('arts', '예체능'), ('photography', '사진/영상/UCC'), ('etc', '기타')], default='', verbose_name='프로젝트 분야')),
                ('target', models.TextField(default='', verbose_name='프로젝트 대상')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='프로젝트 시작일')),
                ('end_date', models.DateField(blank=True, verbose_name='프로젝트 종료일')),
                ('host_org', models.TextField(default='', verbose_name='주관기관')),
                ('description', models.TextField(default='', null=True, verbose_name='프로젝트 설명')),
            ],
        ),
    ]
