# Generated by Django 4.2.23 on 2025-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0004_alter_myprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='project_experience',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='job',
            field=models.CharField(default='학생', max_length=50),
            preserve_default=False,
        ),
    ]
