# Generated by Django 4.2.23 on 2025-06-21 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10)),
                ('region', models.CharField(choices=[('seoul', '서울특별시'), ('busan', '부산광역시'), ('incheon', '인천광역시'), ('daegu', '대구광역시'), ('daejeon', '대전광역시'), ('gwangju', '광주광역시'), ('ulsan', '울산광역시'), ('sejong', '세종특별자치시'), ('gyeonggi', '경기도'), ('chungbuk', '충청북도'), ('chungnam', '충청남도'), ('jeonnam', '전라남도'), ('gyeongbuk', '경상북도'), ('gyeongnam', '경상남도'), ('gangwon', '강원특별자치도'), ('jeonbuk', '전북특별자치도'), ('jeju', '제주특별자치도')], max_length=30)),
                ('district', models.CharField(blank=True, max_length=30)),
                ('education', models.CharField(blank=True, max_length=30, null=True)),
                ('major', models.CharField(blank=True, max_length=30, null=True)),
                ('project_experience', models.CharField(blank=True, max_length=128, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
