# Generated by Django 4.2.23 on 2025-06-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
