# Generated by Django 5.2.3 on 2025-06-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('draft', '임시저장'), ('published', '게시됨')], default='draft', max_length=10),
        ),
    ]
