# Generated by Django 4.2.23 on 2025-06-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_teammember_progress_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='progress',
        ),
        migrations.AddField(
            model_name='team',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
