# Generated by Django 5.2.3 on 2025-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_team_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
