# Generated by Django 5.2.3 on 2025-06-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='project_field',
            field=models.TextField(choices=[('planning', '기획/아이디어'), ('design', '디자인'), ('marketing', '마케팅'), ('arts', '예체능'), ('photography', '사진/영상/UCC'), ('etc', '기타')], default='', verbose_name='프로젝트 분야'),
        ),
    ]
