# Generated by Django 5.2.3 on 2025-06-21 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_post_project_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scrapped_users',
            field=models.ManyToManyField(blank=True, related_name='scrapped_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
